/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define HELLO_WOLRD_PROG ((rpc_uint)0x30000824)
#define HELLO_WORLD_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define HW ((rpc_uint)1)
extern "C" char ** hw_1(void *, CLIENT *);
extern "C" char ** hw_1_svc(void *, struct svc_req *);

#elif __STDC__
#define HW ((rpc_uint)1)
extern  char ** hw_1(void *, CLIENT *);
extern  char ** hw_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define HW ((rpc_uint)1)
extern  char ** hw_1();
extern  char ** hw_1_svc();
#endif /* Old Style C */

#endif /* !_HW_H_RPCGEN */
